Trigger a build of release binder env on mybinder.org
airbus/scikit-decide pull request #156
Opened 2021-12-13 12:19 UTC by nhuet

The goal is to reduce the starting time for real users. Indeed,
according to the mybinder documentation, the build step occurs only the
first time the binderhub launches a jupyter session for a repo with an updated ref. Cf https://mybinder.readthedocs.io/en/latest/about/about.html#what-factors-influence-how-long-it-takes-a-binder-session-to-start

We use a script taken from https://github.com/scikit-hep/pyhf/blob/master/binder/trigger_binder.sh
to ping the endpoints of each binderhub in the mybinder.org federation.
(cf https://mybinder.readthedocs.io/en/latest/about/federation.html)

We do not need to stay connected to the binderhub for the build to go on, so the trigger step in the workflow takes less than 1' as one can see in the workflow generated by a fake release on my fork: https://github.com/nhuet/scikit-decide/runs/4505623076?check_suite_focus=true 
We can see that the build has been done for the commit corresponding to the updated binder environment:
https://mybinder.org/v2/gh/nhuet/scikit-decide/a0e09be06f993f0000b4d6c4a2908f7eec3e266f

(Here you have to trust me for not having follow this link before the workflow took place :)

2021-12-13 23:12 UTC, dbarbier requested changes

2021-12-13 23:12 UTC, dbarbier commented on .github/workflows/release.yml
> +          bash scripts/trigger_binder.sh https://gke.mybinder.org/build/gh/nhuet/scikit-decide/${BINDER_RELEASE_ENV_SHA1}
should not be nhuet there

2021-12-14 08:59 UTC, nhuet commented on .github/workflows/release.yml
> +          bash scripts/trigger_binder.sh https://gke.mybinder.org/build/gh/nhuet/scikit-decide/${BINDER_RELEASE_ENV_SHA1}
:scream:

2021-12-14 09:03 UTC, nhuet commented
Retesting release workflow after correction of repository name in https://github.com/nhuet/scikit-decide/actions/runs/1576990657

2021-12-14 09:42 UTC, dbarbier approved these changes

2021-12-14 12:56 UTC, merged