Build macos wheel on macos-latest github runner
airbus/scikit-decide pull request #212
Opened 2022-09-26 14:08 UTC by nhuet

Macos-10.15 github runner is deprecated and will be removed starting December (cf https://github.com/actions/runner-images/issues/5583). So we need to move the build on macos-latest (= macos-11 currently) and see if tests still pass on macos-10.15.

The other github runner names are also change for their "$os-latest" aliases when possible to follow more easily the update of github runners.

2022-09-26 14:22 UTC, galleon requested changes
Ok for builds done on `latest` but I think tests should still using exact os names `macos-10.15`, `macos-11` and `macos-12`

2022-09-27 15:00 UTC, nhuet commented
I had to work a bit so that the wheel still works on macos 10.15 (it needs at least to have the proper name). I rebase with the solution i found and let the tests as before (not mentioning **-latest in tests oses)

2022-09-27 15:12 UTC, nhuet commented
Nice! The workflow passed this time! And with the requested changes.

2022-09-29 15:25 UTC, galleon approved these changes

2022-09-29 15:27 UTC, merged